version: '3.4'

services:
    mongodbcapabilities:
        image: ${DOCKER_REGISTRY-}mongodbcapabilities
        build:
            context: .
            dockerfile: src/MongoDbCapabilities/Dockerfile
        environment:
            MONGO__USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO__PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO__CONNECTIONSTRING: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017
        depends_on:
            - mongo
        labels:
            - app

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        labels:
            - mongodb

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
        depends_on:
            - mongo
        labels:
            - mongodb
            - tool
