name: Build and Test
on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master
env:
    DOTNET_VERSION: '5.0.100-preview.3.20216.6'
    BUILD_CONFIGURATION: Release
    SOLUTION_TO_BUILD: 'MongoDbCapabilities.sln'
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup .NET Core ${{ env.DOTNET_VERSION }}
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Build
              run: dotnet build ${{ env.SOLUTION_TO_BUILD }} --configuration ${{ env.BUILD_CONFIGURATION }}

            - name: Test
              run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }}
